# register form task
from tkinter import *

root = Tk()

la1 = Label(root, text="username")
la2 = Label(root, text="mobile_no")
la3 = Label(root, text="email_id")
la4 = Label(root, text="age")
la5 = Label(root, text="password")
la6 = Label(root, text="confirm password")
but1 = Button(root, text="login")
but2 = Button(root, text="cancel")

entry1 = Entry(root)
entry2 = Entry(root)
entry3 = Entry(root)
entry4 = Entry(root)
entry5 = Entry(root)
entry6 = Entry(root)

la1.grid(row=0, column=0)
entry1.grid(row=0, column=1)
la2.grid(row=1, column=0)
entry2.grid(row=1, column=1)
la3.grid(row=2, column=0)
entry3.grid(row=2, column=1)
la4.grid(row=3, column=0)
entry4.grid(row=3, column=1)
la5.grid(row=4, column=0)
entry5.grid(row=4, column=1)
la6.grid(row=5, column=0)
entry6.grid(row=5, column=1)

but1.grid(row=6, column=0)
but2.grid(row=6, column=1)
root.mainloop()
# 2eg
# register form task in tkintergrid
from tkinter import *

root = Tk()
la = Label(root, text="register form")
la1 = Label(root, text="username")
la2 = Label(root, text="mobile_no")
la3 = Label(root, text="email_id")
la4 = Label(root, text="age")
la5 = Label(root, text="password")
la6 = Label(root, text="confirm password")
but1 = Button(root, text="login")
but2 = Button(root, text="cancel")

entry1 = Entry(root)
entry2 = Entry(root)
entry3 = Entry(root)
entry4 = Entry(root)
entry5 = Entry(root)
entry6 = Entry(root)
la.grid(row=0, column=0)
la.grid(row=0, column=1)
la1.grid(row=1, column=0)
entry1.grid(row=1, column=1)
la2.grid(row=2, column=0)
entry2.grid(row=2, column=1)
la3.grid(row=3, column=0)
entry3.grid(row=3, column=1)
la4.grid(row=4, column=0)
entry4.grid(row=4, column=1)
la5.grid(row=5, column=0)
entry5.grid(row=5, column=1)
la6.grid(row=6, column=0)
entry6.grid(row=6, column=1)

but1.grid(row=7, column=0)
but2.grid(row=7, column=1)
root.mainloop()
